name: create new version
run-name: create new version by @${{ github.actor }} (${{ inputs.create_release && 'release' || 'dev' }})

on:
  workflow_dispatch:
    inputs:
      create_release:
        type: boolean
        default: false
  push:
    branches:
      - main
      - alpha
      - beta
      - "[0-9]+.x"
      - "[0-9]+.[0-9]+.x"

jobs:
  create-release:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.create_release == true }}
    uses: Pineapple-Of-Evolution/gitops-app/.github/workflows/semantic-release.yaml@main
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: read
    with: {}

  docker-build:
    uses: Pineapple-Of-Evolution/gitops-app/.github/workflows/docker-build-and-push.yaml@main
    if: always()
    permissions:
      contents: write
      packages: write
      id-token: write
    needs: create-release
    with:
      registry: "harbor.labx.pp.ua"
      repository: "ccxt-binance-trade-bot"
      tag: ${{ needs.create-release.outputs.next_version }}
    secrets:
      registry_username: ${{ secrets.HARBOR_USER }}
      registry_password: ${{ secrets.HARBOR_PASS }}
